import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { describe, expect, it } from "vitest";

const root = resolve(process.cwd());

function sourceFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) return sourceFiles(path);
    return /\.(ts|tsx|css|html|md)$/.test(name) ? [path] : [];
  });
}

describe("higiene da versão de produção", () => {
  it("não mantém protótipos de ferramenta de design ou projeto alheio", () => {
    expect(existsSync(resolve(root, "src/features/auth/figma-auth-flow.tsx"))).toBe(false);
    expect(existsSync(resolve(root, "src/features/auth/figma-auth-flow.css"))).toBe(false);
    expect(existsSync(resolve(root, "src/fitfolio-motion.css"))).toBe(false);
  });

  it("não deixa marcas conhecidas de geradores no código de produção", () => {
    const forbidden = [
      /figma\.com\/design/i,
      /data-figma-node/i,
      /\blovable\b/i,
      /\bfitfolio\b/i,
      /generated by chatgpt/i,
      /made with chatgpt/i,
    ];
    const violations: string[] = [];
    for (const path of sourceFiles(resolve(root, "src"))) {
      const content = readFileSync(path, "utf8");
      if (forbidden.some((pattern) => pattern.test(content))) violations.push(relative(root, path));
    }
    expect(violations).toEqual([]);
  });

  it("não expõe modo de demonstração na tela final de identificação", () => {
    const nfc = readFileSync(resolve(root, "src/features/nfc/nfc-screen.tsx"), "utf8");
    expect(nfc).not.toContain("Modo demonstração");
    expect(nfc).not.toContain("TagTrackerDemo");
    expect(nfc).toContain("Iniciar leitura");
  });

  it("mantém o caderno da produção com cache e fila offline", () => {
    const repository = readFileSync(resolve(root, "src/services/family-farming-repository.ts"), "utf8");
    expect(repository).toContain("hydra.production.cache.");
    expect(repository).toContain("hydra.production.queue.");
    expect(repository).toContain("flushProductionQueue");
    expect(repository).toContain('window.addEventListener("online"');
  });
});
