"use client";

import { useEffect, useState, type FormEvent } from "react";
import { CalendarDays, Check, ChevronRight, ClipboardCheck, Pencil, Plus, Trash2 } from "lucide-react";
import { ConfirmDialog, EmptyState, Field, LoadingButton, Modal, ScreenHeader } from "../../components/ui";
import { showAppToast } from "../../components/modal-system";
import { makeId, type Activity, type HydraAccount, type UpdateAccount } from "../../lib/hydra-types";

type Props = { account: HydraAccount; updateAccount: UpdateAccount; onBack: () => void; createRequest?: number; onRequestHandled?: () => void; };

export function ActivitiesScreen({ account, updateAccount, onBack, createRequest, onRequestHandled }: Props) {
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<Activity | null>(null); const [editingId, setEditingId] = useState<string>();
  const [form, setForm] = useState({ title: "", category: "Manejo", customCategory: "", date: new Date().toISOString().slice(0, 10), sectorId: "", animalId: "", note: "" });
  const [error, setError] = useState(""); const [deleteTarget, setDeleteTarget] = useState<Activity | null>(null); const [saving, setSaving] = useState(false); const [deleteBusy, setDeleteBusy] = useState(false); const [deleteError, setDeleteError] = useState("");
  async function save(event: FormEvent) { event.preventDefault(); if (!form.title.trim()) { setError("Dê um nome para a atividade."); return; } const category = form.category === "Personalizada" ? form.customCategory.trim() : form.category; if (!category) { setError("Diga qual é a categoria da atividade."); return; } const next = { id: editingId ?? makeId("activity"), title: form.title.trim(), category, date: form.date, sectorId: form.sectorId || undefined, animalId: form.animalId || undefined, note: form.note.trim() || undefined, done: editingId ? account.activities.find((item) => item.id === editingId)?.done ?? false : false }; setSaving(true); setError(""); try { await updateAccount((current) => ({ ...current, activities: editingId ? current.activities.map((item) => item.id === editingId ? next : item) : [next, ...current.activities] }), { requireRemote: true }); setForm({ title: "", category: "Manejo", customCategory: "", date: new Date().toISOString().slice(0, 10), sectorId: "", animalId: "", note: "" }); setEditingId(undefined); setOpen(false); showAppToast(editingId ? "Atividade atualizada" : "Atividade adicionada à rotina"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não deu para salvar a atividade agora. Tente novamente."); } finally { setSaving(false); } }
  function toggle(item: Activity) { updateAccount((current) => ({ ...current, activities: current.activities.map((activity) => activity.id === item.id ? { ...activity, done: !activity.done } : activity) })); }
  async function remove(item: Activity) { setDeleteBusy(true); setDeleteError(""); try { await updateAccount((current) => ({ ...current, activities: current.activities.filter((activity) => activity.id !== item.id) }), { requireRemote: true }); setSelected(null); setDeleteTarget(null); showAppToast("Atividade removida da rotina"); } catch (caught) { setDeleteError(caught instanceof Error ? caught.message : "Não deu para excluir a atividade agora."); } finally { setDeleteBusy(false); } }
  function openCreate() { setEditingId(undefined); setForm({ title: "", category: "Manejo", customCategory: "", date: new Date().toISOString().slice(0, 10), sectorId: "", animalId: "", note: "" }); setOpen(true); }
  useEffect(() => { if (createRequest !== undefined) { openCreate(); onRequestHandled?.(); } }, [createRequest]);
  function openEdit(item: Activity) { const initialCategories = ['Alimentação', 'Manejo', 'Vacinação', 'Irrigação', 'Plantio', 'Colheita', 'Inspeção', 'Manutenção']; const known = initialCategories.includes(item.category); setEditingId(item.id); setForm({ title: item.title, category: known ? item.category : "Personalizada", customCategory: known ? "" : item.category, date: item.date, sectorId: item.sectorId ?? "", animalId: item.animalId ?? "", note: item.note ?? "" }); setSelected(null); setOpen(true); }
  return <div className="screen page-enter extra-screen">
    <ScreenHeader eyebrow="ROTINA DA PROPRIEDADE" title="Atividades" subtitle="Veja o que precisa ser feito e mantenha a rotina em dia." onBack={onBack} action={<button className="icon-button accent" onClick={openCreate} aria-label="Nova atividade"><Plus size={21} /></button>} />
    <div className="activity-summary"><div><ClipboardCheck size={22} /><span><strong>{account.activities.filter((item) => !item.done).length}</strong><small>para fazer</small></span></div><div><Check size={22} /><span><strong>{account.activities.filter((item) => item.done).length}</strong><small>concluídas</small></span></div></div>
    {account.activities.length === 0 ? <EmptyState icon={<CalendarDays size={27} />} title="Sua rotina está livre por enquanto" text="Quando tiver algo para fazer na propriedade, anote aqui para não esquecer." action={<button className="primary-button" onClick={openCreate}><Plus size={17} /> Adicionar atividade</button>} /> : <div className="activity-list">{account.activities.map((item) => <div className={`activity-card ${item.done ? "done" : ""}`} key={item.id}><button className="activity-check" onClick={() => toggle(item)} aria-label={item.done ? "Voltar para pendentes" : "Marcar como concluída"}>{item.done && <Check size={17} />}</button><button className="activity-main" onClick={() => setSelected(item)}><small>{item.category} · {new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR")}</small><strong>{item.title}</strong><span>{item.note || "Sem observações"}</span></button><ChevronRight size={18} /></div>)}</div>}
    <Modal open={open} onClose={() => { setOpen(false); setEditingId(undefined); setError(""); }} eyebrow={editingId ? "EDITAR" : "NOVA ATIVIDADE"} title={editingId ? "Editar atividade" : "O que precisa ser feito?"} dismissible={!saving}><form className="modal-form" onSubmit={save}><Field label="Atividade"><input value={form.title} onChange={(e) => { setForm({ ...form, title: e.target.value }); setError(""); }} placeholder="Ex.: Vacinar o lote do Pasto 1" autoFocus /></Field><div className="field-combo"><Field label="Categoria"><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{['Alimentação', 'Manejo', 'Vacinação', 'Irrigação', 'Plantio', 'Colheita', 'Inspeção', 'Manutenção', 'Personalizada'].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Quando?"><input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></Field></div>{form.category === "Personalizada" && <Field label="Nome da categoria"><input value={form.customCategory} onChange={(e) => setForm({ ...form, customCategory: e.target.value })} placeholder="Ex.: Cerca e manutenção" /></Field>}<Field label="Onde? (opcional)"><select value={form.sectorId} onChange={(e) => setForm({ ...form, sectorId: e.target.value })}><option value="">Toda a propriedade</option>{account.sectors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Animal (opcional)"><select value={form.animalId} onChange={(e) => setForm({ ...form, animalId: e.target.value })}><option value="">Nenhum animal específico</option>{account.animals.map((item) => <option key={item.id} value={item.id}>{item.name || item.identification}</option>)}</select></Field><Field label="Anotação"><textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} placeholder="Algum detalhe importante?" /></Field>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-action-row"><button className="secondary-button" type="button" onClick={() => setOpen(false)} disabled={saving}>Cancelar</button><LoadingButton className="primary-button" type="submit" loading={saving} loadingLabel="Salvando...">{editingId ? "Salvar alterações" : "Adicionar à rotina"}</LoadingButton></div></form></Modal>
    <Modal open={Boolean(selected)} onClose={() => setSelected(null)} eyebrow="ATIVIDADE" title={selected?.title || "Detalhes"}>{selected && <div className="activity-detail"><span>{selected.category}</span><p>{selected.note || "Nenhuma anotação nesta atividade."}</p><small>{new Date(`${selected.date}T12:00:00`).toLocaleDateString("pt-BR")}</small><div className="detail-actions"><button className="secondary-button" onClick={() => openEdit(selected)}><Pencil size={17} /> Editar</button><button className="danger-button" onClick={() => { setDeleteError(""); setDeleteTarget(selected); }}><Trash2 size={17} /> Excluir</button></div></div>}</Modal>
    <ConfirmDialog open={Boolean(deleteTarget)} title="Excluir esta atividade?" text={`“${deleteTarget?.title || "Atividade"}” será removida da sua rotina.`} confirmLabel="Excluir atividade" busy={deleteBusy} error={deleteError} onCancel={() => { setDeleteTarget(null); setDeleteError(""); }} onConfirm={() => deleteTarget ? remove(deleteTarget) : Promise.resolve()} />
  </div>;
}
